---
- hosts: localhost
  connection: local
  become: no

  vars:
    apt_package_list:
      - wget

    # App store apps
    apple_appstore_package_list:
      - "1295203466" # Microsoft Remote Desktop

    carstick_name: CARTUNES
    homebrew_cask_password_vault: 1password

    personal_bin: "{{ansible_env.HOME}}/bin"
    get_fonts: true
    docker: true
    ruby: true
    google_cloud: true
    projects_dir: "{{ansible_env.HOME}}/Projects"
    projects_dir_personal: "{{projects_dir}}/Personal"
    projects_dir_work: "{{projects_dir}}/Work"
    shell: bash

  tasks:
    - name: Copy albums to destination volume
      copy: src="{{ tunes_library }}/{{ item }}"
        dest="{{ mount_home }}/{{ carstick_name }}"
      with_items: "{{ album_list }}"
